apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: edusprint-tls
  namespace: default  # Make sure this is the same namespace as your ingress
spec:
  secretName: edusprint-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: edusprint.shop
  dnsNames:
    - edusprint.shop
